version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./pdf:/app/pdf
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama-data:
